[package]
name = "mathart"
version = "0.1.0"
edition = "2021"
authors = ["LI Rui<me@lirui.tech>"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gif = "0.11"