name: Run tests

on:
  push:
    branches:
      - master

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
      # - name: Setup Rust
      #   uses: actions-rs/toolchain@v1
      #   with:
      #     override: true
      #     toolchain: stable
      - name: Setup other envs
        run: |
          sudo apt update
          sudo apt install -y cmake gcc-10 openjdk-11-jre maven
          python -m pip install -r requirements_test.txt
          python -m pip install -r Python/requirements.txt
      - name: Run tests
        working-directory: tests
        run: python ./run_tests.py --verbose
